# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [1]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [5]:
s=0
grades = [77, 85, 56, 90, 66]
for i in grades:
    s+=i
print ("average = {0:6.2f}, sum = {1}".format(s/len(grades),s))
#print(f"average = {s/len(grades):6.2f}, sum = {s}")
"""簡單來說，在 .format() 的世界裡，大括號 {} 就像是**「叫號機」，而它後面括號裡的東西就是在「排隊的客人」**。

我們來拆解您的這行程式碼：
print("average = {0:6.2f}, sum = {1}".format(s/len(grades), s))

1. {0} 的 0 是什麼意思？
在程式設計的世界裡，我們數數字通常是從 0 開始數的。
所以 .format() 後面的括號裡，排隊的順序是這樣的：

0 號客人： s/len(grades) (這是平均值)

1 號客人： s (這是總和)

當字串裡寫著 {0} 時，Python 就會去叫 0 號客人 優先入座。也就是把 s/len(grades) 算出來的結果填進去。（後面的 :6.2f 則是順便規定這位客人要穿什麼衣服：總共佔 6 個字元寬，並且保留 2 位小數）。

2. sum 為什麼接 {1}，而不是直接寫 {s}？
因為這整句話是用雙引號 " " 包起來的字串。在雙引號裡面，Python 只會把它當作「純文字」，它根本不認識 s 是個變數。

如果您直接寫 {s}，Python 會去 .format() 裡面找有沒有一位名字叫 s 的客人，結果找不到，就會報錯。

所以我們必須用**「位置號碼」**來叫人： {1} 的意思就是「請把排在第 1 號位置的客人（也就是變數 s）請到這個位子來」。"""

average =  74.80, sum = 374


'簡單來說，在 .format() 的世界裡，大括號 {} 就像是**「叫號機」，而它後面括號裡的東西就是在「排隊的客人」**。\n\n我們來拆解您的這行程式碼：\nprint("average = {0:6.2f}, sum = {1}".format(s/len(grades), s))\n\n1. {0} 的 0 是什麼意思？\n在程式設計的世界裡，我們數數字通常是從 0 開始數的。\n所以 .format() 後面的括號裡，排隊的順序是這樣的：\n\n0 號客人： s/len(grades) (這是平均值)\n\n1 號客人： s (這是總和)\n\n當字串裡寫著 {0} 時，Python 就會去叫 0 號客人 優先入座。也就是把 s/len(grades) 算出來的結果填進去。（後面的 :6.2f 則是順便規定這位客人要穿什麼衣服：總共佔 6 個字元寬，並且保留 2 位小數）。\n\n2. sum 為什麼接 {1}，而不是直接寫 {s}？\n因為這整句話是用雙引號 " " 包起來的字串。在雙引號裡面，Python 只會把它當作「純文字」，它根本不認識 s 是個變數。\n\n如果您直接寫 {s}，Python 會去 .format() 裡面找有沒有一位名字叫 s 的客人，結果找不到，就會報錯。\n\n所以我們必須用**「位置號碼」**來叫人： {1} 的意思就是「請把排在第 1 號位置的客人（也就是變數 s）請到這個位子來」。'

### 【示範】陣列導向

In [16]:
grades = [77, 85, 56, 90, 66]
a=np.array(grades)
print(arr)
a.mean().item() #.item() 會直接把這個物件裡「唯一的那個數字」抽出來，並自動轉成標準的 Python 數字型態。

[77 85 56 90 66]


74.8

最大值

In [11]:
a.max()

np.int64(90)

標準差

In [10]:
a.std()

np.float64(12.416118556135006)

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [19]:
prices = [1096.95, 596.95, 896.95]
usd2twd=31.71
twd=[]
for i in prices:
    twd.append(i*usd2twd)
print(twd)


[34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [21]:
prices = [1096.95, 596.95, 896.95]
prices=np.array(prices)
usd2twd=31.71
prices*usd2twd
#twd=prices*usd2twd
#print(twd)


array([34784.2845, 18929.2845, 28442.2845])

哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [23]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [25]:
grades*weights #r陣列運算不像純數運算~

array([85., 70., 80.])

### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [28]:
weighted_grades=grades*weights
weighted_grades.sum().item()

77.5

### 【技巧】 一行完成成績計算

In [30]:
np.dot(grades,weights).item()

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [72]:
a =np.random.rand(50)
a

array([0.33132323, 0.42460316, 0.76013518, 0.133869  , 0.617398  ,
       0.56338645, 0.16345575, 0.26801566, 0.94284858, 0.91155388,
       0.51469843, 0.58168425, 0.57722547, 0.40516306, 0.43808401,
       0.98314791, 0.39250079, 0.48453434, 0.21967886, 0.1698363 ,
       0.34525787, 0.26191525, 0.24359757, 0.45251496, 0.46124612,
       0.79742459, 0.40963373, 0.39162884, 0.90718985, 0.67604909,
       0.73738132, 0.9806541 , 0.54071083, 0.1507231 , 0.40016407,
       0.51009538, 0.48380068, 0.90184604, 0.73977411, 0.47452573,
       0.95397354, 0.90103907, 0.00699001, 0.4325453 , 0.34871507,
       0.76024838, 0.38396159, 0.40800508, 0.20116743, 0.49575798])

### 【技巧】 檢查 A 的 `shape`

In [61]:
a.shape

(5, 10)

### 【技巧】 更改 A 的 shape

In [73]:
a.shape=(5,10)
a

array([[0.33132323, 0.42460316, 0.76013518, 0.133869  , 0.617398  ,
        0.56338645, 0.16345575, 0.26801566, 0.94284858, 0.91155388],
       [0.51469843, 0.58168425, 0.57722547, 0.40516306, 0.43808401,
        0.98314791, 0.39250079, 0.48453434, 0.21967886, 0.1698363 ],
       [0.34525787, 0.26191525, 0.24359757, 0.45251496, 0.46124612,
        0.79742459, 0.40963373, 0.39162884, 0.90718985, 0.67604909],
       [0.73738132, 0.9806541 , 0.54071083, 0.1507231 , 0.40016407,
        0.51009538, 0.48380068, 0.90184604, 0.73977411, 0.47452573],
       [0.95397354, 0.90103907, 0.00699001, 0.4325453 , 0.34871507,
        0.76024838, 0.38396159, 0.40800508, 0.20116743, 0.49575798]])

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [68]:
b=a.reshape(5,10)
print(a)
print(b)


[[0.51291083 0.20670181 0.11290554 0.60381484 0.45931842 0.19220259
  0.62610394 0.8797429  0.0084676  0.83342874]
 [0.98043609 0.72953099 0.8600445  0.4030086  0.3578177  0.1742706
  0.87460585 0.57382014 0.44292023 0.30203339]
 [0.97526833 0.3903889  0.04926206 0.32911315 0.6507326  0.29940285
  0.32459794 0.45235457 0.59056052 0.58307393]
 [0.47978599 0.95688312 0.04649644 0.45133127 0.62171677 0.36868122
  0.90180982 0.89173882 0.68651119 0.91875697]
 [0.44579371 0.16787759 0.669862   0.80691546 0.34262312 0.69154917
  0.83880819 0.44295979 0.31648265 0.15776366]]
[[0.51291083 0.20670181 0.11290554 0.60381484 0.45931842 0.19220259
  0.62610394 0.8797429  0.0084676  0.83342874]
 [0.98043609 0.72953099 0.8600445  0.4030086  0.3578177  0.1742706
  0.87460585 0.57382014 0.44292023 0.30203339]
 [0.97526833 0.3903889  0.04926206 0.32911315 0.6507326  0.29940285
  0.32459794 0.45235457 0.59056052 0.58307393]
 [0.47978599 0.95688312 0.04649644 0.45133127 0.62171677 0.36868122
  0.90180982 

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [79]:
c=b.ravel()
print(c)
"""
a.ravel() (省記憶體的分身)： 它通常只會建立一個「視角 (View)」。意思是，它沒有真的創造出新的資料，只是換個角度看。⚠️ 警告：如果您修改了 ravel() 產生的一維陣列，原本的二維陣列也會跟著被改變！
a.flatten() (安全的影分身)： 它會老老實實地複製出一份「全新的、獨立的」一維陣列 (Copy)。這會多消耗一點記憶體，但您不管怎麼修改新的陣列，都絕對不會影響到原本的資料，實戰中通常比較安全。
"""

[0.51291083 0.20670181 0.11290554 0.60381484 0.45931842 0.19220259
 0.62610394 0.8797429  0.0084676  0.83342874 0.98043609 0.72953099
 0.8600445  0.4030086  0.3578177  0.1742706  0.87460585 0.57382014
 0.44292023 0.30203339 0.97526833 0.3903889  0.04926206 0.32911315
 0.6507326  0.29940285 0.32459794 0.45235457 0.59056052 0.58307393
 0.47978599 0.95688312 0.04649644 0.45133127 0.62171677 0.36868122
 0.90180982 0.89173882 0.68651119 0.91875697 0.44579371 0.16787759
 0.669862   0.80691546 0.34262312 0.69154917 0.83880819 0.44295979
 0.31648265 0.15776366]


'\na.ravel() (省記憶體的分身)： 它通常只會建立一個「視角 (View)」。意思是，它沒有真的創造出新的資料，只是換個角度看。⚠️ 警告：如果您修改了 ravel() 產生的一維陣列，原本的二維陣列也會跟著被改變！\na.flatten() (安全的影分身)： 它會老老實實地複製出一份「全新的、獨立的」一維陣列 (Copy)。這會多消耗一點記憶體，但您不管怎麼修改新的陣列，都絕對不會影響到原本的資料，實戰中通常比較安全。\n'

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [83]:
np.zeros(10)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [82]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

In [84]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [87]:
x=np.linspace(0,10,100) #0~10中間100個點
x

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### 【技巧】`range` 的 array 版

就是 `arange`。

In [89]:
np.arange(1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列(row)後行(col)」就可以!

我們先弄個 array 來練習。

In [90]:
A=np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [93]:
a_sum=A.sum(axis=0)
print(a_sum)


[ 5  7  9 11 13]


### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [94]:
a_sum=A.sum(axis=1)
print(a_sum)

[10 35]


### 【提示】當然也有可能全部算

In [96]:
A.sum().item()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [97]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [100]:
c = np.array([True,False,False,True,True,False])

[ True False False  True  True False]


這是做啥呢? 我們可以瞬間...

In [102]:
L[c]

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [103]:
L>0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [105]:
L[L>0] #就不用再多說C

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [107]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
x[3:7]

array([3, 4, 5, 6])

### 【技巧】2維陣列切法

記得先列後行!

In [113]:
x=x.reshape(2,5)

要所有的row, 切出行 1-3 位置。

In [118]:
x1=x[:, 1:3]
print(x1)

[[1 2]
 [6 7]]


要所有的行col, 切出第 1 列row!

In [121]:
x2=x[1,:]
print(x2)

[5 6 7 8 9]


## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [124]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [126]:
X=np.c_[x,y]
X

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [127]:
Y=np.r_[x,y]
Y

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [132]:
X[1:2,0:2]

array([[2, 6]])